backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - name: 'knit'
    label: 'Knit'
    folder: 'content/knit'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', required: false, widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Detail', name: 'detail', widget: 'markdown' }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Alt, name: alt, required: false, widget: alt}
      - label: "Material"
        name: "material"
        widget: "list"
        fields:
          - {label: Text, name: text, widget: string}
          - {label: Link, name: link, required: false, widget: string}
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["knit", "crochet", "pattern"]
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["hat","sock","children"]
  - name: "front"
    label: "Front"
    files:
      - label: "Front Page"
        name: "front"
        file: "content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Descriptions, name: descriptions, widget: string}
          - {label: "My Work Title 0", name: myWorkTitle0, widget: string}
          - {label: "My Work Description 0", name: myWorkDescription0, widget: string}
          - {label: "My Work Title 1", name: myWorkTitle1, widget: string}
          - {label: "My Work Description 1", name: myWorkDescription1, widget: string}
          - {label: "My Work Title 2", name: myWorkTitle2, widget: string}
          - {label: "My Work Description 2", name: myWorkDescription2, widget: string}
          - {label: "My Work Title 3", name: myWorkTitle3, widget: string}
          - {label: "My Work Description 3", name: myWorkDescription3, widget: string}
          - {label: "Me Title", name: meTitle, widget: string}
          - {label: "Me Description", name: meDescription, widget: string}